title: "Milkshake"
description: "Simple, minimal and responsive jekyll theme for blogs or personal websites"

base_link: '/'
links:
  - name: About
    link: /about
  - name: Blog
    link: /blog

configuration:
  display: #this is for showing sections
    usage: true # this mean the usage section is enable 
    index_helper: true # which of: "Go to _config.yml for changing this text"