# for creating post:
# - 1) just go to _post folder and creating md file (like default) -be sure its name is look like defaults-
# - 2) fill the objects which of top of the page
# - 3) just writing something
# thats it!

title: "Milkshake"
description: "Simple, minimal and responsive jekyll theme for blogs or personal websites"
baseurl: /milkshake
url: "https://hmtcelik.github.io/"


# for navigation
links:
  - name: About
    link: /about
  - name: Blog
    link: /blog

configuration:
  display: #this is for showing sections
    usage: true # this mean the usage section is enable 
    index_helper: true # which of: "Go to _config.yml for..."

social_links:
  github: "https://github.com/hmtcelik"
  twitter: "https://www.twitter.com/"
  facebook: https://www.facebook.com/
  instagram: "https://www.instagram.com/"


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag